Fixed POST user/register so that Facebook email is copied to email field
Now handle authentication exceptions and return a JSON error message,
e.g:
{
code: 1
error: "Invalid username / password"
}